name: "Publish @lukekaalim/act-renderer-core"

on:
  push:
    tags:
      - '@lukekaalim/act-renderer-core@*'

jobs:
  publish-render-three:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public --workspace=renderers/core
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
